kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm 

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update 
  - cd registrator && git checkout swarm-mode
- name: docker  
  image: plugins/docker
  settings:
    username: drone
    password: ^:zD.hsU#2>EBuzj
    repo: 402/rpi-registrator
    registry: registry.402.at:5000
    auto_tag: true
    dockerfile: registrator/Dockerfile
