kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm 

steps:
- name: submodules
  image: registry.402.at/git
  commands:
  - git submodule update --recursive --remote && cd registrator && git checkout swarm-mode
- name: docker  
  image: plugins/docker
  settings:
    username: docker
    password: test
    repo: registry.402.at/402/rpi-registrator
    registry: https://registry.402.at
    auto_tag: true
    dockerfile: registrator/Dockerfile

image_pull_secrets:
- dockerconfigjson    